//! The port is pinned to the Python path that produced the published numbers.
//!
//! Fixtures are generated by `scripts/export_head_safetensors.py` from a real
//! head and real backbone states. If this test fails, the Rust read-out has
//! drifted from the one every result in the papers was computed through, and
//! the Rust number is the wrong one.
//!
//! The fixture head is 16MB and is not in git. Regenerate it before trusting a
//! change here; without it these tests report that they were skipped, which is
//! not the same as passing.
//!
//! ```text
//! python scripts/export_head_safetensors.py \
//!     --head checkpoints/gemma4_readout/qwen3b_v6_head.pt \
//!     --states artifacts/nla/q4/qwen3b_caches/sc_txt_states_qwen3b.npz \
//!     --modality txt --out rust/srt-geometry/tests/fixtures
//! ```

use srt_geometry::{cosine, Axis, Head, Index, Modality};

const TOL: f32 = 2e-3;

fn fixtures() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn load_head() -> Option<Head> {
    let p = fixtures().join("head.safetensors");
    if !p.exists() {
        // A skip that passes silently is the same hazard this test exists to
        // catch, so CI sets SRT_REQUIRE_FIXTURES=1 and gets a failure instead.
        if std::env::var("SRT_REQUIRE_FIXTURES").is_ok() {
            panic!(
                "SRT_REQUIRE_FIXTURES is set but no fixture at {}; \
                 run scripts/export_head_safetensors.py",
                p.display()
            );
        }
        eprintln!(
            "SKIPPED: no fixture at {}. Regenerate with scripts/export_head_safetensors.py \
             before relying on this test.",
            p.display()
        );
        return None;
    }
    Some(Head::from_safetensors_path(p).expect("load head"))
}

#[test]
fn projection_matches_python_reference() {
    let Some(head) = load_head() else { return };
    let raw = std::fs::read_to_string(fixtures().join("projection_fixture.json"))
        .expect("read fixture");
    let fx: serde_json::Value = serde_json::from_str(&raw).unwrap();

    let modality = match fx["modality"].as_str().unwrap() {
        "Image" => Modality::Image,
        _ => Modality::Text,
    };
    assert_eq!(head.input_dim(modality), fx["d_in"].as_u64().unwrap() as usize);
    assert_eq!(head.proj_dim(), fx["d_out"].as_u64().unwrap() as usize);

    let states = fx["states"].as_array().unwrap();
    let expected = fx["expected"].as_array().unwrap();
    let mut worst = 1.0f32;
    for (s, e) in states.iter().zip(expected) {
        let state: Vec<f32> = s.as_array().unwrap()
            .iter().map(|x| x.as_f64().unwrap() as f32).collect();
        let want: Vec<f32> = e.as_array().unwrap()
            .iter().map(|x| x.as_f64().unwrap() as f32).collect();
        let got = head.project(&state, modality);
        let c = cosine(&got, &want);
        worst = worst.min(c);
        let max_abs = got.iter().zip(&want).map(|(a, b)| (a - b).abs()).fold(0.0f32, f32::max);
        assert!(max_abs < TOL, "elementwise drift {max_abs} exceeds {TOL}");
    }
    assert!(worst > 1.0 - 1e-4, "cosine to reference dropped to {worst}");
}

#[test]
fn recalibration_changes_the_projection_and_is_the_only_state_it_changes() {
    let Some(head0) = load_head() else { return };
    let mut head1 = head0.clone();
    let d = head0.input_dim(Modality::Text);
    let shifted: Vec<f32> = head0.anchor(Modality::Text).iter().map(|x| x + 0.05).collect();
    head1.recalibrate(&shifted, Modality::Text).unwrap();

    let state: Vec<f32> = (0..d).map(|i| ((i % 17) as f32 - 8.0) * 0.01).collect();
    let a = head0.project(&state, Modality::Text);
    let b = head1.project(&state, Modality::Text);
    assert!(cosine(&a, &b) < 0.9999, "anchor swap must move the projection");

    // the image side is untouched by a text-side recalibration
    let si: Vec<f32> = (0..head0.input_dim(Modality::Image)).map(|i| (i as f32) * 1e-3).collect();
    let ia = head0.project(&si, Modality::Image);
    let ib = head1.project(&si, Modality::Image);
    assert!(cosine(&ia, &ib) > 0.99999, "image side must be unaffected");
}

#[test]
fn steering_reorders_retrieval_and_a_matched_random_axis_does_not_reproduce_it() {
    // Two clusters in read-out space; the axis points from one to the other.
    let dim = 64;
    let mut idx = Index::new(dim);
    let mut cluster = |tag: &str, base: usize, n: usize, idx: &mut Index| {
        for i in 0..n {
            let mut v = vec![0.0f32; dim];
            v[base] = 1.0;
            v[(base + 1 + i) % dim] = 0.35;
            idx.add(format!("{tag}{i}"), v).unwrap();
        }
    };
    cluster("a", 0, 8, &mut idx);
    cluster("b", 32, 8, &mut idx);

    let mut query = vec![0.0f32; dim];
    query[0] = 1.0;
    let plain = idx.search(&query, 4);
    assert!(plain.iter().all(|(k, _)| k.starts_with('a')));

    let mut axis_v = vec![0.0f32; dim];
    axis_v[32] = 1.0;
    axis_v[0] = -1.0;
    let axis = Axis::from_vec("a_to_b", axis_v);

    let steered = idx.search(&axis.apply(&query, 2.0), 4);
    assert!(steered.iter().all(|(k, _)| k.starts_with('b')),
            "steering should carry the query to the other cluster: {steered:?}");

    // the control: same norm, random direction, should not perform the move
    let rnd = axis.random_like(7);
    let rnd_hits = idx.search(&rnd.apply(&query, 2.0), 4);
    let moved = rnd_hits.iter().filter(|(k, _)| k.starts_with('b')).count();
    assert!(moved < 4, "a random axis reproduced the steering effect: {rnd_hits:?}");
}
